### ISSUE TITLE
Nodei.co not sending proper cache headers?

### ISSUE THREAD

**Issue by trusktr** [rvagg/nodei.co#20]
I've updated my repo, but when I check my README on github, the badge is outdated due to GitHub's user content caching. If you could fix this, that'd be great! Thanks! Here's a github doc describing the exact problem: https://help.github.com/articles/why-do-my-images-have-strange-urls/#an-image-that-changed-recently-is-not-updating

**Comment by rvagg** [comment]
thanks @trusktr, I had `Cache-Control: max-age=60` but it's now `no-cache`. Please let me know if you have further problems with it

**Comment by trusktr** [comment]
I don't see the new image yet, but maybe it's because it hasn't been an hour yet. https://github.com/infamous/infamous

**Comment by rvagg** [comment]
possibly because their cache is stuck on the old version, you can force it by appending a query string to it, just `?` would do if you don't already have a query string, otherwise just append some garbage to the end of it and their cache will see it as a new image and re-fetch. Also that page you linked me to above has a way that you can apparently expire images from their cache.

**Comment by trusktr** [comment]
@rvagg When I visit https://nodei.co/npm/infamous.png, should I be seeing the new version? I'm still seeing 0.0.16, but expecting 0.0.19. I've cleared my browser cache.

**Comment by trusktr** [comment]
I also tried https://nodei.co/npm/infamous.png?blah=laskdfhaslkdjfhaslkdfhj randomly, but it's still the same.

**Comment by rvagg** [comment]
ok, that could be a persistent but on my end with the cache, it sometimes gets stuck.. I'll clear it out

**Comment by trusktr** [comment]
Sweet, it works now. Thanks!

**Comment by marcellodesales** [comment]
Hi Rod @rvagg 

I'm having the same problem... I have the following:

* Module @ 1.0.0 https://www.npmjs.com/package/istanbul-cobertura-badger
* Badge @ 0.0.4

![badge](https://nodei.co/npm/istanbul-cobertura-badger.png?downloads=true&downloadRank=true&stars=true)

Could you clear this as well?

thanks
