### ISSUE TITLE
Enhancement: Only display the most recently published version of the `latest` tag

### ISSUE THREAD

**Issue by DamonOehlman** [rvagg/nodei.co#23]
Just did a patch to an older version of a package and then published an update under a different tag using `npm publish --tag previous-stable` but nodei.co still picked this up as the latest version.

Happy to make the change, and I've had a bit of a poke around the source haven't found the exact place to make the change.  Will have another look later :)

**Comment by rvagg** [comment]
@DamonOehlman is this still a problem? I'm looking at the code to fetch version and it's going `latest` tag lookup, perhaps that changed after this issue filed (also it's in code not on github cause I split it into 3 repos and haven't got around to publishing them yet)

**Comment by DamonOehlman** [comment]
If you are looking at code and think it should be ok, then feel free to close this issue. I can't even remember which package I noticed this on (was probably `rtc-quickconnect`), but I doubt it's a problem now...
