### ISSUE TITLE
Recent issue with query string

### ISSUE THREAD

**Issue by thaiat** [rvagg/nodei.co#25]
Looks like there is an issue with query string 
the following url does not work:
```
https://nodei.co/npm/generator-mcfly.png?downloads=true&downloadRank=true&stars=true
```

![NPM](https://nodei.co/npm/generator-mcfly.png?downloads=true&downloadRank=true&stars=true)

this one works
```
https://nodei.co/npm/generator-mcfly.png
```

![NPM](https://nodei.co/npm/generator-mcfly.png)

**Comment by rvagg** [comment]
try again, I think this is related to a resource leak, I've restarted everything and it should be going now

**Comment by j3lte** [comment]
Same problem here, I don't see the png

**Comment by rvagg** [comment]
should be fixed now, still some work to do though
