### ISSUE TITLE
Download rank is 'undefined'

### ISSUE THREAD

**Issue by s0ph1e** [rvagg/nodei.co#27]
![after](https://cloud.githubusercontent.com/assets/2333969/8439386/704caf64-1f74-11e5-8af0-d3fa0eec9cdd.png)

**Comment by rvagg** [comment]
thanks @s0ph1e, temporary disabled while I figure this one out

**Comment by pilsy** [comment]
Need some help @rvagg ?

**Comment by rvagg** [comment]
coming back online, I've just done a big upgrade and it _should_ be calculating ranking within the next 12 hours or so when it's collected all the data (data collection is throttled to be kind to npm)
