### ISSUE TITLE
No download count on some modules

### ISSUE THREAD

**Issue by simontabor** [rvagg/nodei.co#28]
Just been adding this to a few of my projects and it seems to work perfectly most of the time, but on one the download count is showing 0 when it should be 400.

Package: [QP](https://www.npmjs.com/package/qp)
![NPM](https://nodei.co/npm/qp.png?downloads=true&downloadRank=true&stars=true)

Screenshot (just in case): ![Screenshot](https://cloud.githubusercontent.com/assets/1441031/8536197/f37b403c-2445-11e5-9302-0d6a6847cff8.png)

Any ideas?

**Comment by rvagg** [comment]
yeah, download counts are a bit messed up since an upgrade of the storage mechanism, for now I'd suggest keeping it off where you know it's inaccurate but feel free to keep pinging me if you don't get action on this! thanks for reporting and sorry it's not working so great

**Comment by BinaryMuse** [comment]
Ah, thanks. I noticed this too after a comment in mojombo/toml#337. Should this correct itself after a while?

**Comment by jdalton** [comment]
I'll :+1:, I found this useful.

**Comment by XadillaX** [comment]
Still messed up?

[![Toshihiko](https://nodei.co/npm/toshihiko.png?downloads=true&downloadRank=true)](https://www.npmjs.org/package/toshihiko) [![Toshihiko](https://nodei.co/npm-dl/toshihiko.png?months=6&height=3)](https://nodei.co/npm-dl/toshihiko.png?months=6&height=3)

**Comment by mathiask88** [comment]
Yup, update on this would be nice :+1:

**Comment by rvagg** [comment]
coming back online, I've just done a big upgrade and it should be calculating ranking within the next 12 hours or so when it's collected all the data (data collection is throttled to be kind to npm)

also I might document the JSON API that anyone can use to inspect the numbers it stores, including the download ranks, it'd be interesting to see if others have use for this
