### ISSUE TITLE
Is it down for good?

### ISSUE THREAD

**Issue by eush77** [rvagg/nodei.co#30]
![nodei.co is down](https://cloud.githubusercontent.com/assets/4472489/9628277/748b5b4a-5172-11e5-8337-b16373454eee.png)

**Comment by rvagg** [comment]
eeek! thanks for reporting! I'll have to get some monitoring onto this, I didn't know. The underlying VM was screwed, needed a hard restart.

**Comment by dylants** [comment]
This is weird, I know the doj.me reports that the site is up, but I've been unable to hit it for a couple days (though a simple ping works).  The browser reports `ERR_CONNECTION_RESET`.

**Comment by rvagg** [comment]
up again, my new status alerts didn't pick it up either for some reason, had to result to someone reporting it via twitter

will get this sorted soon, taking some time off to tend to my side projects shortly

**Comment by dylants** [comment]
@rvagg thanks for doing this, very much appreciate the work!

**Comment by inh3** [comment]
Is this down again?

![screen shot 2015-09-28 at 10 40 40 am](https://cloud.githubusercontent.com/assets/1555148/10143469/692a7bc2-65cd-11e5-9a71-f70f9d82e188.png)

**Comment by rvagg** [comment]
aye aye aye! sorry all, not sure why my status checking service didn't notify might set up another
