### ISSUE TITLE
Add a URL param to make the badge display `npm install -g` instead of `npm install` 

### ISSUE THREAD

**Issue by jakub-g** [rvagg/nodei.co#35]
There are some packages that are command line tools etc. and they are generally to be installed globally.

It would be cool to have an option to have it reflected on the badge.

@rvagg will you be willing to accept a PR for that?

**Comment by rvagg** [comment]
this happens already if you have `"preferGlobal": true` in package.json, e.g.

![ender](https://nodei.co/npm/ender.png)

**Comment by jakub-g** [comment]
ah cool, thx for quick reply!
