### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Richienb** [rvagg/nodei.co#46]
[nodei.co](https://nodei.co/) is responding with:

502 Bad Gateway
nginx/1.10.3 (Ubuntu)

// @rvagg

**Comment by Richienb** [comment]
Fixed.

**Comment by rvagg** [comment]
yeah, sorry @Richienb, I did see this issue and I got a downtime notification but had to spend some time cleaning up a mess on the server to get it back up again and then promptly forgot to come here and close the issue, thanks for reporting tho
