### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by ZEUSGMJ** [rvagg/nodei.co#49]
So I got to know about nodei today, And when I tried to use it, It returned a 502 Response.
```
502 Bad Gateway
```

**Comment by HGlab01** [comment]
![image](https://user-images.githubusercontent.com/54232526/102015518-78ecc300-3d5c-11eb-9f01-700c0b7e3304.png)

**Comment by rvagg** [comment]
doh! sorry, I got an alert but was busy at the time ... fixed now
